### ISSUE TITLE
highfive <2.1 is too restrictive

### ISSUE THREAD

**Issue by zhihaoy** [conda-forge/xtensor-io-feedstock#7]
Conda-forge highfive is on 2.1.1

**Comment by wolfv** [comment]
did you test that xtensor-io still works fine with highfive 2.1.1? If yes, feel free to make a PR to lift that restriction :)

**Comment by zhihaoy** [comment]
Not sure, I wasn't using xtensor-io's h5 support at this point; I'm merely installing them together :/

**Comment by JohanMabille** [comment]
Fixed in #9
